name: Deploy Aries-V

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    env:
      NODE_VERSION: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600 # ajuste o tempo limite conforme necessário
          error_count: 10 # ajuste o número de tentativas de reinicialização após erros
          reporting_interval: 30000 # ajuste o intervalo de relatório de erro conforme necessário
          artifact_name: dist # ajuste o nome do artefato conforme necessário
